import { useState } from "react";
import {
  Alert,
  AlertDescription,
  AlertIcon,
  AlertTitle,
  Button,
  ButtonGroup,
  Collapse,
  Flex,
  Icon,
  IconButton,
  Radio,
  RadioGroup,
  Stack,
  Text,
} from "@chakra-ui/react";
import { generate } from "random-words";
import { IconType } from "react-icons";
import { GiRobotAntennas, GiHouseKeys, GiCog } from "react-icons/gi";

import TypedPhrase from "./TypedPhrase";
import { useDescription } from "../clients/openai";
import CopyButton from "./CopyButton";
import ConfigSlider from "./ConfigSlider";

const TemperatureValues = [0.5, 1.5] as const;
export type TemperatureModes = (typeof TemperatureValues)[number];

interface PassphraseConfig {
  maxLength: number;
  wordCount: number;
  temperature: TemperatureModes;
}

const Content = () => {
  const [currentPassphrase, setCurrentPassphrase] = useState<string | null>(
    null,
  );
  const [isConfigOpen, setIsConfigOpen] = useState(false);
  const [passphraseConfig, setPassphraseConfig] = useState<PassphraseConfig>({
    maxLength: 5,
    wordCount: 4,
    temperature: TemperatureValues[0],
  });

  const toggleConfig = () => {
    setIsConfigOpen((openState) => !openState);
  };

  const updatePassphrase = ({ maxLength, wordCount }: PassphraseConfig) => {
    const nextPassphrase = generate({
      minLength: 3,
      maxLength,
      exactly: wordCount,
      join: " ",
    });
    setCurrentPassphrase(nextPassphrase);
  };

  const { description, isLoading, isError, refetch } = useDescription(
    currentPassphrase,
    passphraseConfig.temperature,
  );

  const handleMaxLengthChange = (nextMaxLength: number) => {
    setPassphraseConfig((priorConfig) => ({
      ...priorConfig,
      maxLength: nextMaxLength,
    }));
  };

  const handleWordCountChange = (nextWordCount: number) => {
    setPassphraseConfig((priorConfig) => ({
      ...priorConfig,
      wordCount: nextWordCount,
    }));
  };

  const handleTemperatureChange = (nextTemperature: string) => {
    // Safe to assert here as we're only passing stringified values from the type
    const nextTemperatureAsNumber = Number(nextTemperature) as TemperatureModes;
    setPassphraseConfig((priorConfig) => ({
      ...priorConfig,
      temperature: nextTemperatureAsNumber,
    }));
  };

  return (
    <Flex
      as="main"
      direction="column"
      justify="center"
      minWidth={[100, 200, 400, 600]}
    >
      {currentPassphrase && (
        <Flex direction="row" align="center">
          <Icon
            boxSize={[6, 12]}
            marginRight="0.5rem"
            as={GiHouseKeys as IconType}
            aria-label="A set of keys symbolizing a phrase to use a password"
          />
          <Flex
            direction="row"
            justify="space-between"
            align="center"
            width="100%"
          >
            <TypedPhrase
              phrase={currentPassphrase}
              ariaLabel={`A set of random words: "${currentPassphrase}"`}
            />
            <CopyButton
              textToCopy={currentPassphrase}
              ariaLabel="Copy passphrase"
            />
          </Flex>
        </Flex>
      )}
      {isError && (
        <Alert status="error" margin="0.5rem 0">
          <AlertIcon />
          <Flex direction="column">
            <AlertTitle fontSize={["0.5rem", "0.75rem"]}>
              Error fetching description.
            </AlertTitle>
            <AlertDescription fontSize={["0.5rem", "0.75rem"]}>
              Please try again later
            </AlertDescription>
          </Flex>
        </Alert>
      )}
      {!isError && description && (
        <Flex direction="row" align="center">
          <Icon
            boxSize={[6, 12]}
            marginRight="0.5rem"
            as={GiRobotAntennas as IconType}
            aria-label="A robot indicating the description is generated by AI"
          />
          <Flex
            direction="row"
            justify="space-between"
            align="center"
            width="100%"
          >
            <TypedPhrase
              phrase={description}
              ariaLabel={`An AI generated mnemonic for the random words "${currentPassphrase}": ${description}`}
              containerOptions={{
                fontFamily: "SFMono-Regular,Menlo,Monaco,Consolas,monospace",
              }}
            />
            <CopyButton textToCopy={description} ariaLabel="Copy description" />
          </Flex>
        </Flex>
      )}
      <Collapse
        in={isConfigOpen}
        transition={{ exit: { duration: 0.3 }, enter: { duration: 0.3 } }}
      >
        <Flex
          direction="column"
          align="flex-start"
          marginTop="2rem"
          padding={"0.5rem"}
        >
          <ConfigSlider
            title="Max Word Length"
            minValue={3}
            maxValue={5}
            step={1}
            value={passphraseConfig.maxLength}
            onChange={handleMaxLengthChange}
          />
          <ConfigSlider
            title="Word Count"
            minValue={3}
            maxValue={5}
            step={1}
            value={passphraseConfig.wordCount}
            onChange={handleWordCountChange}
          />
          <Text fontSize={[".5rem", "1rem"]} marginBottom="0.5rem">
            AI Mode
          </Text>
          <RadioGroup
            name="AI Mode"
            onChange={handleTemperatureChange}
            value={`${passphraseConfig.temperature}`}
          >
            <Stack direction="column">
              <Radio value={TemperatureValues[0].toString()} size="sm">
                Standard
              </Radio>
              <Radio value={TemperatureValues[1].toString()} size="sm">
                Matthew McConaughey
              </Radio>
            </Stack>
          </RadioGroup>
        </Flex>
      </Collapse>
      <ButtonGroup
        marginTop={["0.5rem", "1rem", "2rem"]}
        orientation="vertical"
        alignItems="flex-start"
        width="fit-content"
      >
        <ButtonGroup
          isAttached
          orientation="horizontal"
          alignItems="center"
          width="100%"
        >
          <Button
            colorScheme="red"
            onClick={() => {
              updatePassphrase(passphraseConfig);
            }}
            size={["xs", "sm", "md"]}
            aria-label="Generate a new passphrase"
            width="100%"
          >
            {`Make me ${!currentPassphrase ? "one" : "another"}`}
          </Button>
          <IconButton
            colorScheme="red"
            variant={"outline"}
            size={["xs", "sm", "md"]}
            aria-label="Passphrase configuration"
            onClick={toggleConfig}
            icon={<GiCog />}
          />
        </ButtonGroup>
        {currentPassphrase && (
          <Button
            colorScheme="blue"
            isLoading={isLoading}
            size={["xs", "sm", "md"]}
            aria-label="Regenerate the passphrase description"
            onClick={refetch}
          >
            Regenerate AI mnemonic
          </Button>
        )}
      </ButtonGroup>
    </Flex>
  );
};

export default Content;
